### PR TITLE
Replicate the derivation recipes/templates from Swift

### PR DESCRIPTION
**Pull request by UppaJung**
See equivalent classes in the currently-poorly-named Derivables.swift file and the DerivationRecipeTemplates.swift file.

Realized a separate DerivationRecipeTemplate class was not necessary as the templates are themselves recipes.  Might push that change back to swift at some point.

This doesn't have tests yet.  Created a new issue for that.  Might be a good task for @iOSMahesh
https://github.com/dicekeys/dicekeys-android/issues/38

### CODE REVIEW

**Review by angelix — APPROVED** [review]
Maybe its better to create the Json with Kotlin Serialization than manipulating a string

**Comment by angelix** [comment]
> Maybe its better to create the Json with Kotlin Serialization than manipulating a string

Check #46

**Comment by UppaJung** [comment]
> Maybe its better to create the Json with Kotlin Serialization than manipulating a string

It's actually very important that we hard code the strings and only modify them via a common append function.

There are many valid ways to serialize an object, but since the JSON string is an input to the hash function, a change to a single character will change the password.  If the Android input is different from the iOS input, they will generate different passwords. The user will be unable to recover a password generated with the iOS app from the Android app and vice versa.  If the Kotlin serialization code changed (e.g. ordering fields differently or changing spacing), we could also be unable to replicate the old behavior and unable to re-generate passwords.

So, we have a very intentional approach of generating JSON templates in the TypeScript spec generation project, then only modifying them by appending fields to the end with no spaces.  (e.g. adding ,`"lengthInBytes":64` just before the closing '}'.

**Comment by UppaJung** [comment]
@angelix , if explanation makes sense to you (which is now included in the auto-generated code), please merge.

**Pull request merged**
